In [3]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from pandas_datareader import data as pdr
import yfinance as yf
import numpy as np
import datetime as dt
import matplotlib.pyplot as plt
plt.style.use('seaborn-colorblind')  
%matplotlib inline

In [4]:
# This function is for 4 shares  downloaded from yfinance .. facing some error while doing on dataset. but function is dere


In [5]:


# Create our portfolio of equities
tickers = ['AAPL','FB', 'C', 'DIS']
 
# Download closing prices
data = pdr.get_data_yahoo(tickers, start="2018-01-01", end=dt.date.today())['Close']
 


In [6]:
# From the closing prices, calculate periodic returns
returns = data.pct_change()

# Preview the data
data.tail()
print(returns)

Symbols         AAPL        FB         C       DIS
Date                                              
2018-01-02       NaN       NaN       NaN       NaN
2018-01-03 -0.000174  0.017914  0.003093  0.004293
2018-01-04  0.004645 -0.001841  0.012334 -0.000445
2018-01-05  0.011385  0.013671 -0.001324 -0.005435
2018-01-08 -0.003714  0.007653 -0.011670 -0.014334
...              ...       ...       ...       ...
2022-03-25  0.003734  0.010247  0.005672  0.001295
2022-03-28  0.005037  0.007979 -0.014452 -0.003019
2022-03-29  0.019134  0.028042  0.009836  0.026384
2022-03-30 -0.006650 -0.008744 -0.026563 -0.009973
2022-03-30  0.000000  0.000000  0.000000  0.000000

[1070 rows x 4 columns]


In [7]:
returns = data.pct_change()
returns

Symbols         AAPL        FB         C       DIS
Date                                              
2018-01-02       NaN       NaN       NaN       NaN
2018-01-03 -0.000174  0.017914  0.003093  0.004293
2018-01-04  0.004645 -0.001841  0.012334 -0.000445
2018-01-05  0.011385  0.013671 -0.001324 -0.005435
2018-01-08 -0.003714  0.007653 -0.011670 -0.014334
...              ...       ...       ...       ...
2022-03-25  0.003734  0.010247  0.005672  0.001295
2022-03-28  0.005037  0.007979 -0.014452 -0.003019
2022-03-29  0.019134  0.028042  0.009836  0.026384
2022-03-30 -0.006650 -0.008744 -0.026563 -0.009973
2022-03-30  0.000000  0.000000  0.000000  0.000000

[1070 rows x 4 columns]

In [8]:
# Define function to calculate returns, volatility
def portfolio_annualized_performance(weights, mean_returns, cov_matrix):
    # Given the avg returns, weights of equities calc. the portfolio return
    returns = np.sum(mean_returns*weights ) *252
    # Standard deviation of portfolio (using dot product against covariance, weights)
    # 252 trading days
    std = np.sqrt(np.dot(weights.T, np.dot(cov_matrix, weights))) * np.sqrt(252)
    return std, returns

In [9]:
def generate_random_portfolios(num_portfolios, mean_returns, cov_matrix, risk_free_rate):
    # Initialize array of shape 3 x N to store our results, 
    # where N is the number of portfolios we're going to simulate
    results = np.zeros((3,num_portfolios))
    # Array to store the weights of each equity
    weight_array = []
    for i in range(num_portfolios):
        # Randomly assign floats to our 4 equities
        weights = np.random.random(4)
        # Convert the randomized floats to percentages (summing to 100)
        weights /= np.sum(weights)
        # Add to our portfolio weight array
        weight_array.append(weights)
        # Pull the standard deviation, returns from our function above using 
        # the weights, mean returns generated in this function
        portfolio_std_dev, portfolio_return = portfolio_annualized_performance(weights, mean_returns, cov_matrix)
        # Store output
        results[0,i] = portfolio_std_dev
        results[1,i] = portfolio_return
        # Sharpe ratio
        results[2,i] = (portfolio_return - risk_free_rate) / portfolio_std_dev
    return results ,weight_array #results

In [10]:
returns = data.pct_change()
mean_returns = returns.mean()
cov_matrix = returns.cov()
# Number of portfolios to simulate
num_portfolios = 10000
# Risk free rate (used for Sharpe ratio below)
# anchored on treasury bond rates
risk_free_rate = 0.018

In [11]:
generate_random_portfolios(num_portfolios, mean_returns, cov_matrix, risk_free_rate)

(array([[0.28127079, 0.28133712, 0.27887156, ..., 0.27744908, 0.27732921,
         0.29452972],
        [0.11223628, 0.14128751, 0.13168997, ..., 0.12837835, 0.16239119,
         0.08466065],
        [0.33503757, 0.43821984, 0.4076786 , ..., 0.39783282, 0.52064906,
         0.22632911]]),
 [array([0.02840483, 0.25770221, 0.067995  , 0.64589796]),
  array([0.19994032, 0.30236354, 0.28411315, 0.213583  ]),
  array([0.1644963 , 0.27740157, 0.27217784, 0.28592429]),
  array([0.06316117, 0.49759106, 0.37695023, 0.06229754]),
  array([0.17832739, 0.34416744, 0.28559804, 0.19190714]),
  array([0.08360244, 0.02979644, 0.50539836, 0.38120275]),
  array([0.27139314, 0.27429107, 0.1785329 , 0.2757829 ]),
  array([0.14934165, 0.36280346, 0.13025905, 0.35759584]),
  array([0.4013262 , 0.09970757, 0.2249624 , 0.27400383]),
  array([0.4471329 , 0.40887885, 0.08046291, 0.06352534]),
  array([0.17137057, 0.2925469 , 0.18106961, 0.35501292]),
  array([0.11568429, 0.27429398, 0.17058714, 0.43943459]),
  